apiVersion: v1
kind: Service
metadata:
  name: ipk-calculator-service
  namespace: dev
spec:
  selector:
    app: ipk-calculator
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
